server:
  port: 8080

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/carenest
    username: carenest
    password: carenest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true